name: simCLR

num_epochs: 500
lr: 5e-4
hidden_dim: 128
batch_size: 128
temperature: 0.07
weight_decay: 1e-4

defaults:
  - _self_
  - data: cityscapes
  - location: pc
  - diffusion: ldm_based
  - style_sampling: nearby
  - style_agg: linear
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .